global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'bookstore-consul-discovery'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    consul_sd_configs:
      - server: 'bookstore-consul-discovery:8500' # Host Ip where Consul is running.
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        action: keep
      - source_labels: ['__meta_consul_service']
        target_label: job