server:
  port: ${SERVER_PORT:4001}

security:
  jwt:
    key-store: classpath:JWTKeystore.p12
    key-store-password: devdcorespass
    key-pair-alias: jwt-key
    key-pair-password: devdcorespass
    public-key: classpath:jwt-signing-public-key.txt

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-account-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: account_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.devd.spring.*: DEBUG

management:
  endpoint:
    hystrix:
      stream:
        enabled: true

---

spring:
  profiles: mysql, local
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://freedb.tech:3306/freedbtech_camerashopdb
    username: freedbtech_bershka
    password: 10122000

---

spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://freedb.tech:3306/freedbtech_camerashopdb
    username: freedbtech_bershka
    password: 10122000

